stages:
  - build

build-container:
  stage: build
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
  script:
    - docker build -t ghcr.io/mjfi2sb3/kmer-gwas-cpp:$CI_COMMIT_TAG .
    - docker push ghcr.io/mjfi2sb3/kmer-gwas-cpp:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
