#DW jobdw type=scratch access_mode=striped capacity=1TiB
#DW stage_in type=file source=/project/k1616/Guotai/gwas/rawdata/sequence_data/ACCESSION_REPLACE/ACCESSION_REPLACE_1.fq.gz destination=$DW_JOB_STRIPED/data/ACCESSION_REPLACE_1.fq.gz
#DW stage_in type=file source=/project/k1616/Guotai/gwas/rawdata/sequence_data/ACCESSION_REPLACE/ACCESSION_REPLACE_2.fq.gz destination=$DW_JOB_STRIPED/data/ACCESSION_REPLACE_2.fq.gz
#DW stage_in type=file source=/scratch/bougous/kmer_gwas/build/kmer_count_k51_c200k destination=$DW_JOB_STRIPED/kmer_count_k51_c200k
#DW stage_in type=file source=/scratch/bougous/kmer_gwas/build/kmer_count_k51_c200k_debug destination=$DW_JOB_STRIPED/kmer_count_k51_c200k_debug
#DW stage_in type=file source=/scratch/bougous/kmer_gwas/kmer_gwas_shaheen2_bb.sh destination=$DW_JOB_STRIPED/kmer_gwas_shaheen2_bb.sh
#DW stage_in type=file source=/scratch/bougous/kmer_gwas/kmer_gwas_shaheen2_bb_himem_nomultithread.sh destination=$DW_JOB_STRIPED/kmer_gwas_shaheen2_bb_himem_nomultithread.sh
#DW stage_in type=file source=/scratch/bougous/kmer_gwas/config/bb_ACCESSION_REPLACE.conf destination=$DW_JOB_STRIPED/config/bb_ACCESSION_REPLACE.conf
#DW stage_out type=directory destination=/scratch/bougous/kmer_gwas/output source=$DW_JOB_STRIPED/output/

